// <auto-generated />
using System;
using LogickeHry;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogickeHry.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LogickeHry.SudokuZadani", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("obtiznost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("sudoku");
                });

            modelBuilder.Entity("LogickeHry.Uzivatel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("HashHesla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pohlavi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vek")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("uzivatele");
                });

            modelBuilder.Entity("LogickeHry.vysledek_hry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("cas")
                        .HasColumnType("int");

                    b.Property<string>("hra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("obtiznost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("uzivatelId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("uzivatelId");

                    b.ToTable("statistiky");
                });

            modelBuilder.Entity("SudokuZadaniUzivatel", b =>
                {
                    b.Property<Guid>("UzivatelId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("videlId")
                        .HasColumnType("char(36)");

                    b.HasKey("UzivatelId", "videlId");

                    b.HasIndex("videlId");

                    b.ToTable("SudokuZadaniUzivatel");
                });

            modelBuilder.Entity("LogickeHry.vysledek_hry", b =>
                {
                    b.HasOne("LogickeHry.Uzivatel", "uzivatel")
                        .WithMany()
                        .HasForeignKey("uzivatelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("uzivatel");
                });

            modelBuilder.Entity("SudokuZadaniUzivatel", b =>
                {
                    b.HasOne("LogickeHry.Uzivatel", null)
                        .WithMany()
                        .HasForeignKey("UzivatelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogickeHry.SudokuZadani", null)
                        .WithMany()
                        .HasForeignKey("videlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
